GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
    "title": "Prueba",
    "author": "Anto",
    "url": "https://wikipedia.es",
    "likes": 0
}

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
    "title": "Prueba2",
    "author": "Manu",
    "url": "http://localhost",
    "likes": 0
}

###
POST http://localhost:3003/api/users HTTP/1.1
Content-Type: application/json

{
    "username": "ME",
    "name": "ME AGAIN",
    "password": "1234"
}

###
DELETE http://localhost:3003/api/users/6748a6c94bed579475a1c412 HTTP/1.1